# Generated by Django 3.1.5 on 2021-01-29 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('required', models.BooleanField()),
                ('question_type', models.CharField(choices=[('SA', 'Short Answer'), ('MC', 'Multiple Choice'), ('CB', 'Checkboxes')], default='SA', max_length=2)),
                ('visible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_no', models.CharField(max_length=2)),
                ('item', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questionnaire.question')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponseText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('response_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionresponsedetail')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponseSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionchoice')),
                ('response_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionresponsedetail')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponseMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='questionresponsedetail',
            name='response_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionresponsemaster'),
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaire.questionnaire'),
        ),
    ]
