# Generated by Django 3.1.5 on 2021-01-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionchoice',
            name='choice_no',
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='seq',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
