# Generated by Django 3.1.5 on 2021-01-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20210131_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='seq',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
