# Generated by Django 3.1.5 on 2021-02-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20210218_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
