# Generated by Django 3.1.5 on 2021-02-21 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20210218_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire')),
            ],
            options={
                'unique_together': {('questionnaire', 'question')},
            },
        ),
        migrations.CreateModel(
            name='QuestionChoiceSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question')),
                ('questionchoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionchoice')),
            ],
            options={
                'unique_together': {('question', 'questionchoice')},
            },
        ),
    ]
