# Generated by Django 3.1.5 on 2021-02-21 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20210221_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='seq',
        ),
        migrations.RemoveField(
            model_name='questionchoice',
            name='seq',
        ),
    ]
